import type {
  CardDefinition,
  CreatureCardDefinition,
  SkillCardDefinition,
} from "./schema";

/**
 * The 66 cards in the rules package: 4 Races (Human, Orc, Goblin, Feral) and
 * 2 Classes (Warrior, Mage). Each of the 4 Races has its full 15 cards
 * (ADR-0013). Goblin and Feral have the provisional values of card concepts 6
 * and 7. Each Race has 1 Pivot card (GDD 3.2). The values are printed for
 * Common. GDD section 13 gives the power budget that `balance.ts` checks.
 */
const creatures: readonly CreatureCardDefinition[] = [
  // Human: hold the line.
  {
    kind: "creature",
    id: "human.militiaRecruit",
    race: "human",
    role: "frontliner",
    baseRank: "common",
    countdown: 1,
    attack: 2,
    hp: 4,
    speed: 2,
    range: 0,
    damageType: "physical",
    keywords: {},
  },
  {
    kind: "creature",
    id: "human.shieldbearer",
    race: "human",
    role: "frontliner",
    baseRank: "common",
    countdown: 2,
    attack: 1,
    hp: 7,
    speed: 1,
    range: 0,
    damageType: "physical",
    keywords: {
      armor: 1,
      knockback: { common: 1, epic: 2, legendary: 3 },
    },
  },
  {
    kind: "creature",
    id: "human.crossbowGuard",
    race: "human",
    role: "shooter",
    baseRank: "common",
    countdown: 2,
    attack: 3,
    hp: 4,
    speed: 1,
    range: 3,
    damageType: "physical",
    keywords: {},
  },
  {
    kind: "creature",
    id: "human.halberdier",
    race: "human",
    role: "striker",
    baseRank: "common",
    countdown: 3,
    attack: 4,
    hp: 6,
    speed: 1,
    range: 0,
    damageType: "physical",
    keywords: { retaliation: true },
  },
  {
    kind: "creature",
    id: "human.dawnCleric",
    race: "human",
    role: "support",
    baseRank: "uncommon",
    countdown: 3,
    attack: 2,
    hp: 7,
    speed: 1,
    range: 2,
    damageType: "holy",
    keywords: { regeneration: 1 },
  },
  {
    kind: "creature",
    id: "human.riverKnight",
    race: "human",
    role: "runner",
    baseRank: "uncommon",
    countdown: 4,
    attack: 5,
    hp: 7,
    speed: 2,
    range: 0,
    damageType: "physical",
    keywords: { charge: true },
  },
  {
    kind: "creature",
    id: "human.gateWarden",
    race: "human",
    role: "frontliner",
    baseRank: "uncommon",
    countdown: 3,
    attack: 3,
    hp: 7,
    speed: 1,
    range: 0,
    damageType: "physical",
    keywords: { pivot: true },
  },
  {
    kind: "creature",
    id: "human.ironBulwark",
    race: "human",
    role: "frontliner",
    baseRank: "epic",
    countdown: 6,
    attack: 3,
    hp: 9,
    speed: 1,
    range: 0,
    damageType: "physical",
    keywords: { armor: 2, retaliation: true },
  },
  {
    kind: "creature",
    id: "human.townBarricade",
    race: "human",
    role: "wall",
    baseRank: "common",
    countdown: 1,
    attack: 0,
    hp: 11,
    speed: 0,
    range: 0,
    damageType: "physical",
    keywords: { wall: true },
  },
  {
    kind: "creature",
    id: "human.bridgePikeman",
    race: "human",
    role: "striker",
    baseRank: "uncommon",
    countdown: 3,
    attack: 4,
    hp: 5,
    speed: 1,
    range: 0,
    damageType: "physical",
    keywords: { knockback: { uncommon: 1, epic: 2, legendary: 3 } },
  },
  {
    kind: "creature",
    id: "human.bannerChaplain",
    race: "human",
    role: "support",
    baseRank: "uncommon",
    countdown: 3,
    attack: 2,
    hp: 6,
    speed: 1,
    range: 2,
    damageType: "holy",
    keywords: { rally: 1 },
  },
  {
    kind: "creature",
    id: "human.kingsCourier",
    race: "human",
    role: "runner",
    baseRank: "rare",
    countdown: 4,
    attack: 3,
    hp: 6,
    speed: 4,
    range: 0,
    damageType: "physical",
    keywords: { charge: true },
  },
  {
    kind: "creature",
    id: "human.paviseArbalist",
    race: "human",
    role: "shooter",
    baseRank: "rare",
    countdown: 4,
    attack: 3,
    hp: 4,
    speed: 1,
    range: 4,
    damageType: "physical",
    keywords: { armor: 1, hobble: { rare: 1, epic: 2, legendary: 3 } },
  },
  {
    kind: "creature",
    id: "human.dawnReliquary",
    race: "human",
    role: "wall",
    baseRank: "rare",
    countdown: 4,
    attack: 0,
    hp: 11,
    speed: 0,
    range: 0,
    damageType: "holy",
    keywords: { armor: 2, wall: true, lastBreath: 2 },
  },
  {
    kind: "creature",
    id: "human.marshalElianVoss",
    race: "human",
    role: "support",
    baseRank: "epic",
    countdown: 6,
    attack: 2,
    hp: 7,
    speed: 1,
    range: 2,
    damageType: "holy",
    keywords: { armor: 1, rally: 2, unique: true },
  },
  // Orc: rush the enemy Hero.
  {
    kind: "creature",
    id: "orc.badlandPup",
    race: "orc",
    role: "runner",
    baseRank: "common",
    countdown: 1,
    attack: 3,
    hp: 1,
    speed: 2,
    range: 0,
    damageType: "physical",
    keywords: { lastBreath: 1 },
  },
  {
    kind: "creature",
    id: "orc.scrapRaider",
    race: "orc",
    role: "runner",
    baseRank: "common",
    countdown: 2,
    attack: 3,
    hp: 4,
    speed: 2,
    range: 0,
    damageType: "physical",
    keywords: { heroic: 1, lastBreath: 1 },
  },
  {
    kind: "creature",
    id: "orc.emberShaman",
    race: "orc",
    role: "shooter",
    baseRank: "common",
    countdown: 3,
    attack: 4,
    hp: 6,
    speed: 1,
    range: 3,
    damageType: "fire",
    keywords: {},
  },
  {
    kind: "creature",
    id: "orc.howlingCharger",
    race: "orc",
    role: "striker",
    baseRank: "uncommon",
    countdown: 3,
    attack: 3,
    hp: 5,
    speed: 2,
    range: 0,
    damageType: "physical",
    keywords: { charge: true },
  },
  {
    kind: "creature",
    id: "orc.skyreaver",
    race: "orc",
    role: "runner",
    baseRank: "uncommon",
    countdown: 3,
    attack: 3,
    hp: 4,
    speed: 2,
    range: 0,
    damageType: "physical",
    keywords: { flying: true, heroic: 1 },
  },
  {
    kind: "creature",
    id: "orc.packStalker",
    race: "orc",
    role: "striker",
    baseRank: "uncommon",
    countdown: 2,
    attack: 2,
    hp: 3,
    speed: 2,
    range: 0,
    damageType: "physical",
    keywords: { pivot: true, lastBreath: 1 },
  },
  {
    kind: "creature",
    id: "orc.tuskBrute",
    race: "orc",
    role: "striker",
    baseRank: "common",
    countdown: 4,
    attack: 6,
    hp: 8,
    speed: 1,
    range: 0,
    damageType: "physical",
    keywords: { heroic: 2 },
  },
  {
    kind: "creature",
    id: "orc.warchiefGrukka",
    race: "orc",
    role: "striker",
    baseRank: "epic",
    countdown: 6,
    attack: 4,
    hp: 7,
    speed: 2,
    range: 0,
    damageType: "physical",
    keywords: { charge: true, heroic: 2, unique: true },
  },
  {
    kind: "creature",
    id: "orc.dusthideBrawler",
    race: "orc",
    role: "frontliner",
    baseRank: "common",
    countdown: 2,
    attack: 3,
    hp: 8,
    speed: 1,
    range: 0,
    damageType: "physical",
    keywords: {},
  },
  {
    kind: "creature",
    id: "orc.cinderhornRam",
    race: "orc",
    role: "runner",
    baseRank: "uncommon",
    countdown: 3,
    attack: 3,
    hp: 4,
    speed: 2,
    range: 0,
    damageType: "fire",
    keywords: { charge: true },
  },
  {
    kind: "creature",
    id: "orc.warhowlerDrummer",
    race: "orc",
    role: "support",
    baseRank: "uncommon",
    countdown: 2,
    attack: 2,
    hp: 5,
    speed: 1,
    range: 0,
    damageType: "physical",
    keywords: { rally: 1 },
  },
  {
    kind: "creature",
    id: "orc.ashspitHunter",
    race: "orc",
    role: "shooter",
    baseRank: "rare",
    countdown: 4,
    attack: 4,
    hp: 5,
    speed: 1,
    range: 4,
    damageType: "fire",
    keywords: {},
  },
  {
    kind: "creature",
    id: "orc.mesaPitFighter",
    race: "orc",
    role: "frontliner",
    baseRank: "rare",
    countdown: 4,
    attack: 3,
    hp: 8,
    speed: 1,
    range: 0,
    damageType: "physical",
    keywords: { retaliation: true },
  },
  {
    kind: "creature",
    id: "orc.pyreaxeRavager",
    race: "orc",
    role: "striker",
    baseRank: "rare",
    countdown: 5,
    attack: 5,
    hp: 6,
    speed: 1,
    range: 0,
    damageType: "fire",
    keywords: { heroic: 2 },
  },
  {
    kind: "creature",
    id: "orc.warbandStandardBearer",
    race: "orc",
    role: "support",
    baseRank: "epic",
    countdown: 6,
    attack: 3,
    hp: 6,
    speed: 1,
    range: 0,
    damageType: "physical",
    keywords: { charge: true, heroic: 2, rally: 2 },
  },
  // Goblin: make the enemy plan slower (provisional, card concepts 6).
  {
    kind: "creature",
    id: "goblin.ankleSnatcher",
    race: "goblin",
    role: "runner",
    baseRank: "common",
    countdown: 1,
    attack: 2,
    hp: 2,
    speed: 2,
    range: 0,
    damageType: "physical",
    keywords: { hobble: 1 },
  },
  {
    kind: "creature",
    id: "goblin.fuseRunner",
    race: "goblin",
    role: "runner",
    baseRank: "common",
    countdown: 1,
    attack: 1,
    hp: 2,
    speed: 2,
    range: 0,
    damageType: "physical",
    keywords: { lastBreath: 3 },
  },
  {
    kind: "creature",
    id: "goblin.junkSlinger",
    race: "goblin",
    role: "shooter",
    baseRank: "common",
    countdown: 2,
    attack: 3,
    hp: 3,
    speed: 1,
    range: 3,
    damageType: "physical",
    keywords: { hobble: 1 },
  },
  {
    kind: "creature",
    id: "goblin.tunnelSaboteur",
    race: "goblin",
    role: "support",
    baseRank: "common",
    countdown: 2,
    attack: 2,
    hp: 5,
    speed: 1,
    range: 0,
    damageType: "physical",
    keywords: { sabotage: 1 },
  },
  {
    kind: "creature",
    id: "goblin.scrapPlateGuard",
    race: "goblin",
    role: "frontliner",
    baseRank: "common",
    countdown: 2,
    attack: 2,
    hp: 6,
    speed: 1,
    range: 0,
    damageType: "physical",
    keywords: { armor: 1 },
  },
  {
    kind: "creature",
    id: "goblin.sidestepShiv",
    race: "goblin",
    role: "striker",
    baseRank: "uncommon",
    countdown: 2,
    attack: 2,
    hp: 3,
    speed: 2,
    range: 0,
    damageType: "physical",
    keywords: { pivot: true },
  },
  {
    kind: "creature",
    id: "goblin.junkBarricade",
    race: "goblin",
    role: "wall",
    baseRank: "uncommon",
    countdown: 2,
    attack: 0,
    hp: 10,
    speed: 0,
    range: 0,
    damageType: "physical",
    keywords: { wall: true, sabotage: 1 },
  },
  {
    kind: "creature",
    id: "goblin.bombLobber",
    race: "goblin",
    role: "shooter",
    baseRank: "uncommon",
    countdown: 3,
    attack: 3,
    hp: 3,
    speed: 1,
    range: 3,
    damageType: "fire",
    keywords: {},
  },
  {
    kind: "creature",
    id: "goblin.greaseTrapper",
    race: "goblin",
    role: "support",
    baseRank: "uncommon",
    countdown: 3,
    attack: 3,
    hp: 5,
    speed: 1,
    range: 0,
    damageType: "physical",
    keywords: { hobble: 2, sabotage: 1 },
  },
  {
    kind: "creature",
    id: "goblin.rocketBarrelRider",
    race: "goblin",
    role: "runner",
    baseRank: "uncommon",
    countdown: 3,
    attack: 3,
    hp: 3,
    speed: 3,
    range: 0,
    damageType: "fire",
    keywords: { lastBreath: 2 },
  },
  {
    kind: "creature",
    id: "goblin.mineSapper",
    race: "goblin",
    role: "striker",
    baseRank: "rare",
    countdown: 4,
    attack: 3,
    hp: 4,
    speed: 2,
    range: 0,
    damageType: "fire",
    keywords: { lastBreath: 3 },
  },
  {
    kind: "creature",
    id: "goblin.spyglassSniper",
    race: "goblin",
    role: "shooter",
    baseRank: "rare",
    countdown: 4,
    attack: 3,
    hp: 5,
    speed: 1,
    range: 4,
    damageType: "physical",
    keywords: { sabotage: 1 },
  },
  {
    kind: "creature",
    id: "goblin.junkWalker",
    race: "goblin",
    role: "frontliner",
    baseRank: "rare",
    countdown: 4,
    attack: 3,
    hp: 7,
    speed: 1,
    range: 0,
    damageType: "physical",
    keywords: { armor: 2 },
  },
  {
    kind: "creature",
    id: "goblin.grandGearjammer",
    race: "goblin",
    role: "support",
    baseRank: "epic",
    countdown: 4,
    attack: 2,
    hp: 4,
    speed: 1,
    range: 2,
    damageType: "physical",
    keywords: { sabotage: 2 },
  },
  {
    kind: "creature",
    id: "goblin.bossSnikkit",
    race: "goblin",
    role: "striker",
    baseRank: "epic",
    countdown: 5,
    attack: 3,
    hp: 5,
    speed: 2,
    range: 0,
    damageType: "fire",
    keywords: { unique: true, sabotage: 1, lastBreath: 3 },
  },
  // Feral: few, huge and slow (provisional, card concepts 7).
  {
    kind: "creature",
    id: "feral.bristlebackBoar",
    race: "feral",
    role: "runner",
    baseRank: "common",
    countdown: 2,
    attack: 3,
    hp: 3,
    speed: 2,
    range: 0,
    damageType: "physical",
    keywords: { trample: true },
  },
  {
    kind: "creature",
    id: "feral.cragLizard",
    race: "feral",
    role: "frontliner",
    baseRank: "common",
    countdown: 2,
    attack: 2,
    hp: 7,
    speed: 1,
    range: 0,
    damageType: "physical",
    keywords: { armor: 1 },
  },
  {
    kind: "creature",
    id: "feral.frostfangLynx",
    race: "feral",
    role: "striker",
    baseRank: "common",
    countdown: 2,
    attack: 4,
    hp: 3,
    speed: 1,
    range: 0,
    damageType: "frost",
    keywords: { bleed: { common: 1, epic: 2, legendary: 3 } },
  },
  {
    kind: "creature",
    id: "feral.caveBear",
    race: "feral",
    role: "frontliner",
    baseRank: "common",
    countdown: 3,
    attack: 3,
    hp: 10,
    speed: 1,
    range: 0,
    damageType: "physical",
    keywords: { regeneration: 1 },
  },
  {
    kind: "creature",
    id: "feral.webSpitter",
    race: "feral",
    role: "shooter",
    baseRank: "common",
    countdown: 3,
    attack: 3,
    hp: 8,
    speed: 1,
    range: 3,
    damageType: "physical",
    keywords: { entangle: true },
  },
  {
    kind: "creature",
    id: "feral.boulderTortoise",
    race: "feral",
    role: "wall",
    baseRank: "uncommon",
    countdown: 3,
    attack: 0,
    hp: 12,
    speed: 0,
    range: 0,
    damageType: "physical",
    keywords: { wall: true, armor: 1, regeneration: 2 },
  },
  {
    kind: "creature",
    id: "feral.tailsweepBasilisk",
    race: "feral",
    role: "striker",
    baseRank: "uncommon",
    countdown: 3,
    attack: 3,
    hp: 6,
    speed: 1,
    range: 0,
    damageType: "physical",
    keywords: { pivot: true },
  },
  {
    kind: "creature",
    id: "feral.caveTroll",
    race: "feral",
    role: "frontliner",
    baseRank: "uncommon",
    countdown: 4,
    attack: 3,
    hp: 10,
    speed: 1,
    range: 0,
    damageType: "physical",
    keywords: { regeneration: 2 },
  },
  {
    kind: "creature",
    id: "feral.cragRhino",
    race: "feral",
    role: "striker",
    baseRank: "uncommon",
    countdown: 4,
    attack: 4,
    hp: 8,
    speed: 1,
    range: 0,
    damageType: "physical",
    keywords: { trample: true },
  },
  {
    kind: "creature",
    id: "feral.frostElkMatriarch",
    race: "feral",
    role: "support",
    baseRank: "uncommon",
    countdown: 4,
    attack: 3,
    hp: 9,
    speed: 1,
    range: 0,
    damageType: "frost",
    keywords: { rally: 1 },
  },
  {
    kind: "creature",
    id: "feral.avalancheYeti",
    race: "feral",
    role: "striker",
    baseRank: "rare",
    countdown: 4,
    attack: 4,
    hp: 6,
    speed: 1,
    range: 0,
    damageType: "physical",
    keywords: { trample: true },
  },
  {
    kind: "creature",
    id: "feral.woollyMammoth",
    race: "feral",
    role: "frontliner",
    baseRank: "rare",
    countdown: 5,
    attack: 4,
    hp: 9,
    speed: 1,
    range: 0,
    damageType: "physical",
    keywords: { armor: 1, trample: true },
  },
  {
    kind: "creature",
    id: "feral.rimebreathDrake",
    race: "feral",
    role: "shooter",
    baseRank: "rare",
    countdown: 5,
    attack: 3,
    hp: 6,
    speed: 1,
    range: 3,
    damageType: "frost",
    keywords: { flying: true },
  },
  {
    kind: "creature",
    id: "feral.mountainColossus",
    race: "feral",
    role: "frontliner",
    baseRank: "epic",
    countdown: 6,
    attack: 3,
    hp: 9,
    speed: 1,
    range: 0,
    damageType: "physical",
    keywords: { regeneration: 2, trample: true },
  },
  {
    kind: "creature",
    id: "feral.oldFrostmaw",
    race: "feral",
    role: "striker",
    baseRank: "epic",
    countdown: 6,
    attack: 4,
    hp: 8,
    speed: 1,
    range: 0,
    damageType: "frost",
    keywords: {
      unique: true,
      trample: true,
      bleed: { epic: 2, legendary: 3 },
    },
  },
];

const skills: readonly SkillCardDefinition[] = [
  // Warrior: buffs and tempo.
  {
    kind: "skill",
    id: "warrior.warDrums",
    class: "warrior",
    baseRank: "common",
    countdown: 2,
    target: "none",
    effect: { type: "lowerCountdown", cards: 2, amount: 1 },
  },
  {
    kind: "skill",
    id: "warrior.shieldWall",
    class: "warrior",
    baseRank: "common",
    countdown: 2,
    target: "friendlyLane",
    effect: { type: "laneArmor", armor: 1, turns: 2 },
  },
  {
    kind: "skill",
    id: "warrior.spearThrow",
    class: "warrior",
    baseRank: "uncommon",
    countdown: 3,
    target: "enemyUnit",
    effect: { type: "damageUnit", amount: 4, damageType: "physical" },
  },
  // Mage: area damage.
  {
    kind: "skill",
    id: "mage.fireball",
    class: "mage",
    baseRank: "common",
    countdown: 3,
    target: "enemyUnit",
    effect: { type: "damageArea", amount: 3, damageType: "fire", length: 2 },
  },
  {
    kind: "skill",
    id: "mage.frostBolt",
    class: "mage",
    baseRank: "common",
    countdown: 2,
    target: "enemyUnit",
    effect: { type: "damageUnit", amount: 2, damageType: "frost" },
  },
  {
    kind: "skill",
    id: "mage.flameWave",
    class: "mage",
    baseRank: "uncommon",
    countdown: 4,
    target: "enemyLane",
    effect: { type: "damageLane", amount: 2, damageType: "fire" },
  },
];

export const CARDS: readonly CardDefinition[] = [...creatures, ...skills];

const byId = new Map<string, CardDefinition>(
  CARDS.map((card) => [card.id, card])
);

/** The card definition for an ID. Throws for an unknown ID: content is checked by tests. */
export const getCard = (cardId: string): CardDefinition => {
  const card = byId.get(cardId);
  if (!card) {
    throw new Error(`Unknown card: ${cardId}`);
  }
  return card;
};
