import type {
  CardDefinition,
  CreatureCardDefinition,
  SkillCardDefinition,
} from "./schema";

/**
 * The 23 cards of the Battle slice (roadmap M1): 2 Races
 * (Human, Orc) and 2 Classes (Warrior, Mage). Each Race has 1 Pivot
 * card (GDD 3.2). The values are printed
 * for Common. GDD section 13 gives the power budget that `balance.ts` checks.
 */
const creatures: readonly CreatureCardDefinition[] = [
  // Human: hold the line.
  {
    kind: "creature",
    id: "human.militiaRecruit",
    race: "human",
    role: "frontliner",
    baseRank: "common",
    countdown: 1,
    attack: 2,
    hp: 4,
    speed: 2,
    range: 0,
    damageType: "physical",
    keywords: {},
  },
  {
    kind: "creature",
    id: "human.shieldbearer",
    race: "human",
    role: "frontliner",
    baseRank: "common",
    countdown: 2,
    attack: 1,
    hp: 8,
    speed: 1,
    range: 0,
    damageType: "physical",
    keywords: { armor: 1 },
  },
  {
    kind: "creature",
    id: "human.crossbowGuard",
    race: "human",
    role: "shooter",
    baseRank: "common",
    countdown: 2,
    attack: 3,
    hp: 4,
    speed: 1,
    range: 3,
    damageType: "physical",
    keywords: {},
  },
  {
    kind: "creature",
    id: "human.halberdier",
    race: "human",
    role: "striker",
    baseRank: "common",
    countdown: 3,
    attack: 4,
    hp: 6,
    speed: 1,
    range: 0,
    damageType: "physical",
    keywords: { retaliation: true },
  },
  {
    kind: "creature",
    id: "human.dawnCleric",
    race: "human",
    role: "support",
    baseRank: "uncommon",
    countdown: 3,
    attack: 2,
    hp: 8,
    speed: 1,
    range: 2,
    damageType: "holy",
    keywords: { regeneration: 1 },
  },
  {
    kind: "creature",
    id: "human.riverKnight",
    race: "human",
    role: "runner",
    baseRank: "uncommon",
    countdown: 4,
    attack: 5,
    hp: 8,
    speed: 2,
    range: 0,
    damageType: "physical",
    keywords: { charge: true },
  },
  {
    kind: "creature",
    id: "human.gateWarden",
    race: "human",
    role: "frontliner",
    baseRank: "uncommon",
    countdown: 3,
    attack: 3,
    hp: 9,
    speed: 1,
    range: 0,
    damageType: "physical",
    keywords: { pivot: true },
  },
  {
    kind: "creature",
    id: "human.ironBulwark",
    race: "human",
    role: "frontliner",
    baseRank: "epic",
    countdown: 6,
    attack: 5,
    hp: 15,
    speed: 1,
    range: 0,
    damageType: "physical",
    keywords: { armor: 2, retaliation: true },
  },
  {
    kind: "creature",
    id: "human.paviseArbalist",
    race: "human",
    role: "shooter",
    baseRank: "rare",
    countdown: 4,
    attack: 5,
    hp: 6,
    speed: 1,
    range: 4,
    damageType: "physical",
    keywords: { armor: 1, hobble: { rare: 1, epic: 2, legendary: 3 } },
  },
  // Orc: rush the enemy Hero.
  {
    kind: "creature",
    id: "orc.badlandPup",
    race: "orc",
    role: "runner",
    baseRank: "common",
    countdown: 1,
    attack: 3,
    hp: 1,
    speed: 2,
    range: 0,
    damageType: "physical",
    keywords: { lastBreath: 1 },
  },
  {
    kind: "creature",
    id: "orc.scrapRaider",
    race: "orc",
    role: "runner",
    baseRank: "common",
    countdown: 2,
    attack: 3,
    hp: 4,
    speed: 2,
    range: 0,
    damageType: "physical",
    keywords: { heroic: 1, lastBreath: 1 },
  },
  {
    kind: "creature",
    id: "orc.emberShaman",
    race: "orc",
    role: "shooter",
    baseRank: "common",
    countdown: 3,
    attack: 4,
    hp: 6,
    speed: 1,
    range: 3,
    damageType: "fire",
    keywords: {},
  },
  {
    kind: "creature",
    id: "orc.howlingCharger",
    race: "orc",
    role: "striker",
    baseRank: "uncommon",
    countdown: 3,
    attack: 4,
    hp: 6,
    speed: 2,
    range: 0,
    damageType: "physical",
    keywords: { charge: true },
  },
  {
    kind: "creature",
    id: "orc.skyreaver",
    race: "orc",
    role: "runner",
    baseRank: "uncommon",
    countdown: 3,
    attack: 3,
    hp: 5,
    speed: 2,
    range: 0,
    damageType: "physical",
    keywords: { flying: true, heroic: 1 },
  },
  {
    kind: "creature",
    id: "orc.packStalker",
    race: "orc",
    role: "striker",
    baseRank: "uncommon",
    countdown: 2,
    attack: 3,
    hp: 3,
    speed: 2,
    range: 0,
    damageType: "physical",
    keywords: { pivot: true, lastBreath: 1 },
  },
  {
    kind: "creature",
    id: "orc.tuskBrute",
    race: "orc",
    role: "striker",
    baseRank: "common",
    countdown: 4,
    attack: 6,
    hp: 8,
    speed: 1,
    range: 0,
    damageType: "physical",
    keywords: { heroic: 2 },
  },
  {
    kind: "creature",
    id: "orc.warchiefGrukka",
    race: "orc",
    role: "striker",
    baseRank: "epic",
    countdown: 6,
    attack: 8,
    hp: 12,
    speed: 2,
    range: 0,
    damageType: "physical",
    keywords: { charge: true, heroic: 2 },
  },
];

const skills: readonly SkillCardDefinition[] = [
  // Warrior: buffs and tempo.
  {
    kind: "skill",
    id: "warrior.warDrums",
    class: "warrior",
    baseRank: "common",
    countdown: 2,
    target: "none",
    effect: { type: "lowerCountdown", cards: 2, amount: 1 },
  },
  {
    kind: "skill",
    id: "warrior.shieldWall",
    class: "warrior",
    baseRank: "common",
    countdown: 2,
    target: "friendlyLane",
    effect: { type: "laneArmor", armor: 1, turns: 2 },
  },
  {
    kind: "skill",
    id: "warrior.spearThrow",
    class: "warrior",
    baseRank: "uncommon",
    countdown: 3,
    target: "enemyUnit",
    effect: { type: "damageUnit", amount: 4, damageType: "physical" },
  },
  // Mage: area damage.
  {
    kind: "skill",
    id: "mage.fireball",
    class: "mage",
    baseRank: "common",
    countdown: 3,
    target: "enemyUnit",
    effect: { type: "damageArea", amount: 3, damageType: "fire", length: 2 },
  },
  {
    kind: "skill",
    id: "mage.frostBolt",
    class: "mage",
    baseRank: "common",
    countdown: 2,
    target: "enemyUnit",
    effect: { type: "damageUnit", amount: 2, damageType: "frost" },
  },
  {
    kind: "skill",
    id: "mage.flameWave",
    class: "mage",
    baseRank: "uncommon",
    countdown: 4,
    target: "enemyLane",
    effect: { type: "damageLane", amount: 2, damageType: "fire" },
  },
];

export const CARDS: readonly CardDefinition[] = [...creatures, ...skills];

const byId = new Map<string, CardDefinition>(
  CARDS.map((card) => [card.id, card])
);

/** The card definition for an ID. Throws for an unknown ID: content is checked by tests. */
export const getCard = (cardId: string): CardDefinition => {
  const card = byId.get(cardId);
  if (!card) {
    throw new Error(`Unknown card: ${cardId}`);
  }
  return card;
};
