import type {
  CardDefinition,
  CreatureCardDefinition,
  SkillCardDefinition,
} from "./schema";

/**
 * The 96 cards in the rules package: 6 Races (Human, Orc, Goblin, Feral, Elf,
 * Undead) and 2 Classes (Warrior, Mage). Each of the 6 Races has its full 15
 * cards (ADR-0013). Goblin, Feral, Elf and Undead have the provisional values
 * of card concepts 6, 7, 4 and 5. Each Race has 1 Pivot card (GDD 3.2). The values are
 * printed for Common. GDD section 13 gives the power budget that `balance.ts`
 * checks.
 */
const creatures: readonly CreatureCardDefinition[] = [
  // Human: hold the line.
  {
    kind: "creature",
    id: "human.militiaRecruit",
    race: "human",
    role: "frontliner",
    baseRank: "common",
    countdown: 1,
    attack: 3,
    hp: 8,
    speed: 1,
    range: 0,
    damageType: "physical",
    keywords: {},
  },
  {
    kind: "creature",
    id: "human.shieldbearer",
    race: "human",
    role: "frontliner",
    baseRank: "common",
    countdown: 2,
    attack: 1,
    hp: 7,
    speed: 1,
    range: 0,
    damageType: "physical",
    keywords: {
      armor: 1,
      knockback: { common: 1, epic: 2, legendary: 3 },
    },
  },
  {
    kind: "creature",
    id: "human.crossbowGuard",
    race: "human",
    role: "shooter",
    baseRank: "common",
    countdown: 2,
    attack: 4,
    hp: 5,
    speed: 1,
    range: 3,
    damageType: "physical",
    keywords: {},
  },
  {
    kind: "creature",
    id: "human.halberdier",
    race: "human",
    role: "striker",
    baseRank: "common",
    countdown: 3,
    attack: 4,
    hp: 6,
    speed: 1,
    range: 0,
    damageType: "physical",
    keywords: { retaliate: true },
  },
  {
    kind: "creature",
    id: "human.dawnCleric",
    race: "human",
    role: "support",
    baseRank: "uncommon",
    countdown: 3,
    attack: 2,
    hp: 7,
    speed: 1,
    range: 2,
    damageType: "holy",
    keywords: { regenerate: 1 },
  },
  {
    kind: "creature",
    id: "human.riverKnight",
    race: "human",
    role: "runner",
    baseRank: "uncommon",
    countdown: 4,
    attack: 4,
    hp: 6,
    speed: 2,
    range: 0,
    damageType: "physical",
    keywords: { charge: { uncommon: 1, epic: 2, legendary: 3 } },
  },
  {
    kind: "creature",
    id: "human.gateWarden",
    race: "human",
    role: "frontliner",
    baseRank: "uncommon",
    countdown: 3,
    attack: 3,
    hp: 7,
    speed: 1,
    range: 0,
    damageType: "physical",
    keywords: { pivot: true },
  },
  {
    kind: "creature",
    id: "human.ironBulwark",
    race: "human",
    role: "frontliner",
    baseRank: "epic",
    countdown: 6,
    attack: 2,
    hp: 6,
    speed: 1,
    range: 0,
    damageType: "physical",
    keywords: { armor: 2, retaliate: true },
  },
  {
    kind: "creature",
    id: "human.townBarricade",
    race: "human",
    role: "wall",
    baseRank: "common",
    countdown: 1,
    attack: 0,
    hp: 15,
    speed: 0,
    range: 0,
    damageType: "physical",
    keywords: { wall: true },
  },
  {
    kind: "creature",
    id: "human.bridgePikeman",
    race: "human",
    role: "striker",
    baseRank: "uncommon",
    countdown: 3,
    attack: 4,
    hp: 5,
    speed: 1,
    range: 0,
    damageType: "physical",
    keywords: { knockback: { uncommon: 1, epic: 2, legendary: 3 } },
  },
  {
    kind: "creature",
    id: "human.bannerChaplain",
    race: "human",
    role: "support",
    baseRank: "uncommon",
    countdown: 3,
    attack: 2,
    hp: 6,
    speed: 1,
    range: 2,
    damageType: "holy",
    keywords: { rally: 1 },
  },
  {
    kind: "creature",
    id: "human.kingsCourier",
    race: "human",
    role: "runner",
    baseRank: "rare",
    countdown: 4,
    attack: 2,
    hp: 5,
    speed: 4,
    range: 0,
    damageType: "physical",
    keywords: { charge: { rare: 1, epic: 2, legendary: 3 } },
  },
  {
    kind: "creature",
    id: "human.paviseArbalist",
    race: "human",
    role: "shooter",
    baseRank: "rare",
    countdown: 4,
    attack: 3,
    hp: 6,
    speed: 1,
    range: 3,
    damageType: "physical",
    keywords: { armor: 1, hobble: { rare: 1, epic: 2, legendary: 3 } },
  },
  {
    kind: "creature",
    id: "human.dawnReliquary",
    race: "human",
    role: "wall",
    baseRank: "rare",
    countdown: 4,
    attack: 0,
    hp: 9,
    speed: 0,
    range: 0,
    damageType: "holy",
    keywords: { armor: 2, wall: true, lastBreath: 2 },
  },
  {
    kind: "creature",
    id: "human.marshalElianVoss",
    race: "human",
    role: "support",
    baseRank: "epic",
    countdown: 6,
    attack: 1,
    hp: 6,
    speed: 1,
    range: 2,
    damageType: "holy",
    keywords: { armor: 1, rally: 2, unique: true },
  },
  // Orc: rush the enemy Hero.
  {
    kind: "creature",
    id: "orc.badlandRunt",
    race: "orc",
    role: "runner",
    baseRank: "common",
    countdown: 1,
    attack: 4,
    hp: 1,
    speed: 2,
    range: 0,
    damageType: "physical",
    keywords: { lastBreath: 1 },
  },
  {
    kind: "creature",
    id: "orc.scrapRaider",
    race: "orc",
    role: "runner",
    baseRank: "common",
    countdown: 2,
    attack: 3,
    hp: 4,
    speed: 2,
    range: 0,
    damageType: "physical",
    keywords: { heroic: 1, lastBreath: 1 },
  },
  {
    kind: "creature",
    id: "orc.emberShaman",
    race: "orc",
    role: "shooter",
    baseRank: "common",
    countdown: 3,
    attack: 4,
    hp: 6,
    speed: 1,
    range: 3,
    damageType: "fire",
    keywords: {},
  },
  {
    kind: "creature",
    id: "orc.howlingCharger",
    race: "orc",
    role: "striker",
    baseRank: "uncommon",
    countdown: 3,
    attack: 3,
    hp: 5,
    speed: 2,
    range: 0,
    damageType: "physical",
    keywords: { charge: { uncommon: 1, epic: 2, legendary: 3 } },
  },
  {
    kind: "creature",
    id: "orc.skyreaver",
    race: "orc",
    role: "runner",
    baseRank: "uncommon",
    countdown: 3,
    attack: 3,
    hp: 3,
    speed: 2,
    range: 0,
    damageType: "physical",
    keywords: { flying: true, heroic: 1 },
  },
  {
    kind: "creature",
    id: "orc.packStalker",
    race: "orc",
    role: "striker",
    baseRank: "uncommon",
    countdown: 2,
    attack: 2,
    hp: 4,
    speed: 2,
    range: 0,
    damageType: "physical",
    keywords: { pivot: true, lastBreath: 1 },
  },
  {
    kind: "creature",
    id: "orc.tuskBrute",
    race: "orc",
    role: "striker",
    baseRank: "common",
    countdown: 4,
    attack: 5,
    hp: 7,
    speed: 1,
    range: 0,
    damageType: "physical",
    keywords: { heroic: 2 },
  },
  {
    kind: "creature",
    id: "orc.warchiefGrukka",
    race: "orc",
    role: "striker",
    baseRank: "epic",
    countdown: 6,
    attack: 3,
    hp: 5,
    speed: 2,
    range: 0,
    damageType: "physical",
    keywords: { charge: { epic: 2, legendary: 3 }, heroic: 2, unique: true },
  },
  {
    kind: "creature",
    id: "orc.dusthideBrawler",
    race: "orc",
    role: "frontliner",
    baseRank: "common",
    countdown: 2,
    attack: 3,
    hp: 9,
    speed: 1,
    range: 0,
    damageType: "physical",
    keywords: {},
  },
  {
    kind: "creature",
    id: "orc.cinderhornBreaker",
    race: "orc",
    role: "runner",
    baseRank: "uncommon",
    countdown: 3,
    attack: 3,
    hp: 3,
    speed: 2,
    range: 0,
    damageType: "fire",
    keywords: { charge: { uncommon: 1, epic: 2, legendary: 3 } },
  },
  {
    kind: "creature",
    id: "orc.warhowlerDrummer",
    race: "orc",
    role: "support",
    baseRank: "uncommon",
    countdown: 2,
    attack: 2,
    hp: 7,
    speed: 1,
    range: 0,
    damageType: "physical",
    keywords: { rally: 1 },
  },
  {
    kind: "creature",
    id: "orc.ashspitHunter",
    race: "orc",
    role: "shooter",
    baseRank: "rare",
    countdown: 4,
    attack: 4,
    hp: 4,
    speed: 1,
    range: 3,
    damageType: "fire",
    keywords: {},
  },
  {
    kind: "creature",
    id: "orc.mesaPitFighter",
    race: "orc",
    role: "frontliner",
    baseRank: "rare",
    countdown: 4,
    attack: 3,
    hp: 7,
    speed: 1,
    range: 0,
    damageType: "physical",
    keywords: { retaliate: true },
  },
  {
    kind: "creature",
    id: "orc.pyreaxeRavager",
    race: "orc",
    role: "striker",
    baseRank: "rare",
    countdown: 5,
    attack: 4,
    hp: 5,
    speed: 1,
    range: 0,
    damageType: "fire",
    keywords: { heroic: 2 },
  },
  {
    kind: "creature",
    id: "orc.warbandStandardBearer",
    race: "orc",
    role: "support",
    baseRank: "epic",
    countdown: 6,
    attack: 2,
    hp: 4,
    speed: 1,
    range: 0,
    damageType: "physical",
    keywords: { charge: { epic: 2, legendary: 3 }, heroic: 2, rally: 2 },
  },
  // Goblin: make the enemy plan slower (provisional, card concepts 6).
  {
    kind: "creature",
    id: "goblin.ankleSnatcher",
    race: "goblin",
    role: "runner",
    baseRank: "common",
    countdown: 1,
    attack: 3,
    hp: 3,
    speed: 2,
    range: 0,
    damageType: "physical",
    keywords: { hobble: 1 },
  },
  {
    kind: "creature",
    id: "goblin.fuseRunner",
    race: "goblin",
    role: "runner",
    baseRank: "common",
    countdown: 1,
    attack: 2,
    hp: 4,
    speed: 2,
    range: 0,
    damageType: "physical",
    keywords: { lastBreath: 3 },
  },
  {
    kind: "creature",
    id: "goblin.junkSlinger",
    race: "goblin",
    role: "shooter",
    baseRank: "common",
    countdown: 2,
    attack: 4,
    hp: 4,
    speed: 1,
    range: 3,
    damageType: "physical",
    keywords: { hobble: 1 },
  },
  {
    kind: "creature",
    id: "goblin.tunnelSaboteur",
    race: "goblin",
    role: "support",
    baseRank: "common",
    countdown: 2,
    attack: 3,
    hp: 7,
    speed: 1,
    range: 0,
    damageType: "physical",
    keywords: { sabotage: 1 },
  },
  {
    kind: "creature",
    id: "goblin.scrapPlateGuard",
    race: "goblin",
    role: "frontliner",
    baseRank: "common",
    countdown: 2,
    attack: 3,
    hp: 8,
    speed: 1,
    range: 0,
    damageType: "physical",
    keywords: { armor: 1 },
  },
  {
    kind: "creature",
    id: "goblin.sidestepShiv",
    race: "goblin",
    role: "striker",
    baseRank: "uncommon",
    countdown: 2,
    attack: 3,
    hp: 4,
    speed: 1,
    range: 0,
    damageType: "physical",
    keywords: { pivot: true },
  },
  {
    kind: "creature",
    id: "goblin.junkBarricade",
    race: "goblin",
    role: "wall",
    baseRank: "uncommon",
    countdown: 2,
    attack: 0,
    hp: 12,
    speed: 0,
    range: 0,
    damageType: "physical",
    keywords: { wall: true, sabotage: 1 },
  },
  {
    kind: "creature",
    id: "goblin.bombLobber",
    race: "goblin",
    role: "shooter",
    baseRank: "uncommon",
    countdown: 3,
    attack: 3,
    hp: 3,
    speed: 1,
    range: 3,
    damageType: "fire",
    keywords: {},
  },
  {
    kind: "creature",
    id: "goblin.greaseTrapper",
    race: "goblin",
    role: "support",
    baseRank: "uncommon",
    countdown: 3,
    attack: 3,
    hp: 5,
    speed: 1,
    range: 0,
    damageType: "physical",
    keywords: { hobble: 2, sabotage: 1 },
  },
  {
    kind: "creature",
    id: "goblin.rocketBarrelRider",
    race: "goblin",
    role: "runner",
    baseRank: "uncommon",
    countdown: 3,
    attack: 3,
    hp: 2,
    speed: 3,
    range: 0,
    damageType: "fire",
    keywords: { lastBreath: 2 },
  },
  {
    kind: "creature",
    id: "goblin.mineSapper",
    race: "goblin",
    role: "striker",
    baseRank: "rare",
    countdown: 4,
    attack: 3,
    hp: 5,
    speed: 1,
    range: 0,
    damageType: "fire",
    keywords: { lastBreath: 3 },
  },
  {
    kind: "creature",
    id: "goblin.spyglassSniper",
    race: "goblin",
    role: "shooter",
    baseRank: "rare",
    countdown: 4,
    attack: 3,
    hp: 6,
    speed: 1,
    range: 3,
    damageType: "physical",
    keywords: { sabotage: 1 },
  },
  {
    kind: "creature",
    id: "goblin.junkWalker",
    race: "goblin",
    role: "frontliner",
    baseRank: "rare",
    countdown: 4,
    attack: 3,
    hp: 6,
    speed: 1,
    range: 0,
    damageType: "physical",
    keywords: { armor: 2 },
  },
  {
    kind: "creature",
    id: "goblin.grandGearjammer",
    race: "goblin",
    role: "support",
    baseRank: "epic",
    countdown: 4,
    attack: 2,
    hp: 3,
    speed: 1,
    range: 2,
    damageType: "physical",
    keywords: { sabotage: 2 },
  },
  {
    kind: "creature",
    id: "goblin.bossSnikkit",
    race: "goblin",
    role: "striker",
    baseRank: "epic",
    countdown: 5,
    attack: 2,
    hp: 4,
    speed: 1,
    range: 0,
    damageType: "fire",
    keywords: { unique: true, sabotage: 1, lastBreath: 3 },
  },
  // Feral: few, huge and slow (provisional, card concepts 7).
  {
    kind: "creature",
    id: "feral.bristlebackBoar",
    race: "feral",
    role: "runner",
    baseRank: "common",
    countdown: 2,
    attack: 4,
    hp: 4,
    speed: 2,
    range: 0,
    damageType: "physical",
    keywords: { trample: true },
  },
  {
    kind: "creature",
    id: "feral.cragLizard",
    race: "feral",
    role: "frontliner",
    baseRank: "common",
    countdown: 2,
    attack: 2,
    hp: 8,
    speed: 1,
    range: 0,
    damageType: "physical",
    keywords: { armor: 1 },
  },
  {
    kind: "creature",
    id: "feral.frostfangLynx",
    race: "feral",
    role: "striker",
    baseRank: "common",
    countdown: 2,
    attack: 4,
    hp: 3,
    speed: 1,
    range: 0,
    damageType: "frost",
    keywords: { bleed: { common: 1, epic: 2, legendary: 3 } },
  },
  {
    kind: "creature",
    id: "feral.caveBear",
    race: "feral",
    role: "frontliner",
    baseRank: "common",
    countdown: 3,
    attack: 3,
    hp: 10,
    speed: 1,
    range: 0,
    damageType: "physical",
    keywords: { regenerate: 1 },
  },
  {
    kind: "creature",
    id: "feral.webSpitter",
    race: "feral",
    role: "shooter",
    baseRank: "common",
    countdown: 3,
    attack: 3,
    hp: 8,
    speed: 1,
    range: 3,
    damageType: "physical",
    keywords: { regenerate: 1 },
  },
  {
    kind: "creature",
    id: "feral.boulderTortoise",
    race: "feral",
    role: "wall",
    baseRank: "uncommon",
    countdown: 3,
    attack: 0,
    hp: 12,
    speed: 0,
    range: 0,
    damageType: "physical",
    keywords: { wall: true, armor: 1, regenerate: 2 },
  },
  {
    kind: "creature",
    id: "feral.tailsweepBasilisk",
    race: "feral",
    role: "striker",
    baseRank: "uncommon",
    countdown: 3,
    attack: 3,
    hp: 6,
    speed: 1,
    range: 0,
    damageType: "physical",
    keywords: { pivot: true },
  },
  {
    kind: "creature",
    id: "feral.caveTroll",
    race: "feral",
    role: "frontliner",
    baseRank: "uncommon",
    countdown: 4,
    attack: 3,
    hp: 9,
    speed: 1,
    range: 0,
    damageType: "physical",
    keywords: { regenerate: 2 },
  },
  {
    kind: "creature",
    id: "feral.cragRhino",
    race: "feral",
    role: "striker",
    baseRank: "uncommon",
    countdown: 4,
    attack: 4,
    hp: 8,
    speed: 1,
    range: 0,
    damageType: "physical",
    keywords: { trample: true },
  },
  {
    kind: "creature",
    id: "feral.frostElkMatriarch",
    race: "feral",
    role: "support",
    baseRank: "uncommon",
    countdown: 4,
    attack: 3,
    hp: 7,
    speed: 1,
    range: 0,
    damageType: "frost",
    keywords: { rally: 1 },
  },
  {
    kind: "creature",
    id: "feral.avalancheYeti",
    race: "feral",
    role: "striker",
    baseRank: "rare",
    countdown: 4,
    attack: 4,
    hp: 5,
    speed: 1,
    range: 0,
    damageType: "physical",
    keywords: { trample: true },
  },
  {
    kind: "creature",
    id: "feral.woollyMammoth",
    race: "feral",
    role: "frontliner",
    baseRank: "rare",
    countdown: 5,
    attack: 3,
    hp: 7,
    speed: 1,
    range: 0,
    damageType: "physical",
    keywords: { armor: 1, trample: true },
  },
  {
    kind: "creature",
    id: "feral.rimebreathDrake",
    race: "feral",
    role: "striker",
    baseRank: "rare",
    countdown: 5,
    attack: 3,
    hp: 6,
    speed: 1,
    range: 0,
    damageType: "frost",
    keywords: { flying: true },
  },
  {
    kind: "creature",
    id: "feral.mountainColossus",
    race: "feral",
    role: "frontliner",
    baseRank: "epic",
    countdown: 6,
    attack: 2,
    hp: 7,
    speed: 1,
    range: 0,
    damageType: "physical",
    keywords: { regenerate: 2, trample: true },
  },
  {
    kind: "creature",
    id: "feral.oldFrostmaw",
    race: "feral",
    role: "striker",
    baseRank: "epic",
    countdown: 6,
    attack: 3,
    hp: 6,
    speed: 1,
    range: 0,
    damageType: "frost",
    keywords: {
      unique: true,
      trample: true,
      bleed: { epic: 2, legendary: 3 },
    },
  }, // Elf: control from range, heal and poison.
  {
    kind: "creature",
    id: "elf.rootboundGuard",
    race: "elf",
    role: "frontliner",
    baseRank: "common",
    countdown: 3,
    attack: 3,
    hp: 7,
    speed: 1,
    range: 0,
    damageType: "physical",
    keywords: { armor: 1, regenerate: 1 },
  },
  {
    kind: "creature",
    id: "elf.brambleDuelist",
    race: "elf",
    role: "striker",
    baseRank: "common",
    countdown: 2,
    attack: 5,
    hp: 5,
    speed: 1,
    range: 0,
    damageType: "physical",
    keywords: {},
  },
  {
    kind: "creature",
    id: "elf.fernwingCourier",
    race: "elf",
    role: "runner",
    baseRank: "common",
    countdown: 2,
    attack: 3,
    hp: 3,
    speed: 2,
    range: 0,
    damageType: "physical",
    keywords: { flying: true },
  },
  {
    kind: "creature",
    id: "elf.mosspitcherLookout",
    race: "elf",
    role: "shooter",
    baseRank: "common",
    countdown: 3,
    attack: 3,
    hp: 6,
    speed: 1,
    range: 3,
    damageType: "physical",
    keywords: { regenerate: 1 },
  },
  {
    kind: "creature",
    id: "elf.acornTender",
    race: "elf",
    role: "shooter",
    baseRank: "common",
    countdown: 3,
    attack: 3,
    hp: 3,
    speed: 1,
    range: 3,
    damageType: "holy",
    keywords: { poison: true },
  },
  {
    kind: "creature",
    id: "elf.gladeTurnblade",
    race: "elf",
    role: "striker",
    baseRank: "uncommon",
    countdown: 3,
    attack: 4,
    hp: 4,
    speed: 1,
    range: 0,
    damageType: "physical",
    keywords: { pivot: true },
  },
  {
    kind: "creature",
    id: "elf.canopySkirmisher",
    race: "elf",
    role: "runner",
    baseRank: "uncommon",
    countdown: 3,
    attack: 3,
    hp: 3,
    speed: 2,
    range: 0,
    damageType: "physical",
    keywords: { flying: true },
  },
  {
    kind: "creature",
    id: "elf.thornlineArcher",
    race: "elf",
    role: "shooter",
    baseRank: "uncommon",
    countdown: 3,
    attack: 3,
    hp: 3,
    speed: 1,
    range: 3,
    damageType: "physical",
    keywords: { poison: true },
  },
  {
    kind: "creature",
    id: "elf.dewkeeper",
    race: "elf",
    role: "support",
    baseRank: "uncommon",
    countdown: 3,
    attack: 2,
    hp: 8,
    speed: 1,
    range: 2,
    damageType: "holy",
    keywords: { regenerate: 1 },
  },
  {
    kind: "creature",
    id: "elf.brambleNest",
    race: "elf",
    role: "wall",
    baseRank: "uncommon",
    countdown: 3,
    attack: 0,
    hp: 16,
    speed: 0,
    range: 0,
    damageType: "physical",
    keywords: { wall: true, regenerate: 1 },
  },
  {
    kind: "creature",
    id: "elf.amberwingDart",
    race: "elf",
    role: "runner",
    baseRank: "rare",
    countdown: 3,
    attack: 2,
    hp: 3,
    speed: 2,
    range: 0,
    damageType: "physical",
    keywords: { flying: true, poison: true },
  },
  {
    kind: "creature",
    id: "elf.elderreedDartmaster",
    race: "elf",
    role: "shooter",
    baseRank: "rare",
    countdown: 4,
    attack: 3,
    hp: 7,
    speed: 1,
    range: 3,
    damageType: "physical",
    keywords: { poison: true },
  },
  {
    kind: "creature",
    id: "elf.seedwindShepherd",
    race: "elf",
    role: "support",
    baseRank: "rare",
    countdown: 4,
    attack: 1,
    hp: 7,
    speed: 1,
    range: 2,
    damageType: "holy",
    keywords: { flying: true, regenerate: 1 },
  },
  {
    kind: "creature",
    id: "elf.canopyVinewarden",
    race: "elf",
    role: "shooter",
    baseRank: "epic",
    countdown: 5,
    attack: 3,
    hp: 3,
    speed: 1,
    range: 3,
    damageType: "physical",
    keywords: { firstStrike: true, entangle: true },
  },
  {
    kind: "creature",
    id: "elf.lethielFirstGardener",
    race: "elf",
    role: "support",
    baseRank: "epic",
    countdown: 4,
    attack: 1,
    hp: 6,
    speed: 1,
    range: 2,
    damageType: "holy",
    keywords: { unique: true, regenerate: 2 },
  },
  // Undead: many cheap Units that grow stronger together, come back and bring more.
  {
    kind: "creature",
    id: "undead.graveyardDrudge",
    race: "undead",
    role: "frontliner",
    baseRank: "common",
    countdown: 1,
    attack: 3,
    hp: 6,
    speed: 1,
    range: 0,
    damageType: "physical",
    keywords: { swarm: 1 },
  },
  {
    kind: "creature",
    id: "undead.rattleknife",
    race: "undead",
    role: "striker",
    baseRank: "common",
    countdown: 1,
    attack: 3,
    hp: 6,
    speed: 1,
    range: 0,
    damageType: "physical",
    keywords: { swarm: 1 },
  },
  {
    kind: "creature",
    id: "undead.coffinLidSkater",
    race: "undead",
    role: "runner",
    baseRank: "common",
    countdown: 1,
    attack: 3,
    hp: 6,
    speed: 1,
    range: 0,
    damageType: "physical",
    keywords: { charge: { common: 1, epic: 2, legendary: 3 } },
  },
  {
    kind: "creature",
    id: "undead.hushbow",
    race: "undead",
    role: "shooter",
    baseRank: "common",
    countdown: 2,
    attack: 3,
    hp: 4,
    speed: 1,
    range: 3,
    damageType: "physical",
    keywords: { summon: "token.skeleton" },
  },
  {
    kind: "creature",
    id: "undead.graveBellTender",
    race: "undead",
    role: "support",
    baseRank: "common",
    countdown: 2,
    attack: 3,
    hp: 6,
    speed: 1,
    range: 0,
    damageType: "physical",
    keywords: { summon: "token.skeleton" },
  },
  {
    kind: "creature",
    id: "undead.backwatchBailiff",
    race: "undead",
    role: "frontliner",
    baseRank: "uncommon",
    countdown: 2,
    attack: 3,
    hp: 5,
    speed: 1,
    range: 0,
    damageType: "physical",
    keywords: { pivot: true },
  },
  {
    kind: "creature",
    id: "undead.chatteringCohort",
    race: "undead",
    role: "striker",
    baseRank: "uncommon",
    countdown: 2,
    attack: 3,
    hp: 7,
    speed: 1,
    range: 0,
    damageType: "physical",
    keywords: { swarm: 1 },
  },
  {
    kind: "creature",
    id: "undead.paleGalloper",
    race: "undead",
    role: "runner",
    baseRank: "uncommon",
    countdown: 2,
    attack: 2,
    hp: 4,
    speed: 2,
    range: 0,
    damageType: "frost",
    keywords: { charge: { uncommon: 1, epic: 2, legendary: 3 } },
  },
  {
    kind: "creature",
    id: "undead.rimeEyeReaper",
    race: "undead",
    role: "striker",
    baseRank: "uncommon",
    countdown: 2,
    attack: 3,
    hp: 5,
    speed: 1,
    range: 0,
    damageType: "frost",
    keywords: {},
  },
  {
    kind: "creature",
    id: "undead.ossuaryPiper",
    race: "undead",
    role: "support",
    baseRank: "uncommon",
    countdown: 2,
    attack: 3,
    hp: 5,
    speed: 1,
    range: 0,
    damageType: "physical",
    keywords: { rally: 1 },
  },
  {
    kind: "creature",
    id: "undead.coffinLancer",
    race: "undead",
    role: "frontliner",
    baseRank: "rare",
    countdown: 2,
    attack: 1,
    hp: 4,
    speed: 1,
    range: 0,
    damageType: "physical",
    keywords: { armor: 1, rebirth: true },
  },
  {
    kind: "creature",
    id: "undead.winterMaw",
    race: "undead",
    role: "striker",
    baseRank: "rare",
    countdown: 3,
    attack: 2,
    hp: 4,
    speed: 1,
    range: 0,
    damageType: "frost",
    keywords: { firstStrike: true, swarm: 1 },
  },
  {
    kind: "creature",
    id: "undead.lanternWidow",
    race: "undead",
    role: "support",
    baseRank: "rare",
    countdown: 3,
    attack: 1,
    hp: 4,
    speed: 1,
    range: 0,
    damageType: "frost",
    keywords: { summon: "token.restlessWisp" },
  },
  {
    kind: "creature",
    id: "undead.sirOdoLastTaxman",
    race: "undead",
    role: "striker",
    baseRank: "epic",
    countdown: 4,
    attack: 2,
    hp: 4,
    speed: 1,
    range: 0,
    damageType: "physical",
    keywords: {
      unique: true,
      charge: { epic: 2, legendary: 3 },
      rebirth: true,
    },
  },
  {
    kind: "creature",
    id: "undead.boneRampart",
    race: "undead",
    role: "wall",
    baseRank: "epic",
    countdown: 3,
    attack: 0,
    hp: 5,
    speed: 0,
    range: 0,
    damageType: "physical",
    keywords: { wall: true, armor: 2, rebirth: true },
  },
];

const skills: readonly SkillCardDefinition[] = [
  // Warrior: buffs and tempo.
  {
    kind: "skill",
    id: "warrior.warDrums",
    class: "warrior",
    baseRank: "common",
    countdown: 2,
    target: "none",
    effect: { type: "lowerCountdown", cards: 2, amount: 1 },
  },
  {
    kind: "skill",
    id: "warrior.shieldWall",
    class: "warrior",
    baseRank: "common",
    countdown: 2,
    target: "friendlyLane",
    effect: { type: "laneArmor", armor: 1, turns: 2 },
  },
  {
    kind: "skill",
    id: "warrior.spearThrow",
    class: "warrior",
    baseRank: "uncommon",
    countdown: 3,
    target: "enemyUnit",
    effect: { type: "damageUnit", amount: 4, damageType: "physical" },
  },
  // Mage: area damage.
  {
    kind: "skill",
    id: "mage.fireball",
    class: "mage",
    baseRank: "common",
    countdown: 3,
    target: "enemyUnit",
    effect: { type: "damageArea", amount: 3, damageType: "fire", length: 2 },
  },
  {
    kind: "skill",
    id: "mage.frostBolt",
    class: "mage",
    baseRank: "common",
    countdown: 2,
    target: "enemyUnit",
    effect: { type: "damageUnit", amount: 2, damageType: "frost" },
  },
  {
    kind: "skill",
    id: "mage.flameWave",
    class: "mage",
    baseRank: "uncommon",
    countdown: 4,
    target: "enemyLane",
    effect: { type: "damageLane", amount: 2, damageType: "fire" },
  },
];

export const CARDS: readonly CardDefinition[] = [...creatures, ...skills];

const byId = new Map<string, CardDefinition>(
  CARDS.map((card) => [card.id, card])
);

/** The card definition for an ID. Throws for an unknown ID: content is checked by tests. */
export const getCard = (cardId: string): CardDefinition => {
  const card = byId.get(cardId);
  if (!card) {
    throw new Error(`Unknown card: ${cardId}`);
  }
  return card;
};
